mysite/library/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from .views import  AddView,updateView,deleteView,updatestdView,deletestdView
from django.contrib.auth.views import LoginView

app_name = 'library'

urlpatterns = [
       #for home
       path('',views.home,name = 'home'),
       #for contact
       path('contact/',views.contact,name ='contact' ),
       #for about us
       path('about/',views.about,name='about'),

       # for view book
       path('book/list/',views.booklist,name='book_list'),
       # path('book/list/',booklistview.as_view(),name = 'book_list'),
       #for detail view
       path('detail/<int:id>/', views.bookdetails, name='book_detail'),
       # path('detail/<int:id>/',bookdetailview.as_view(),name='book-detail'),
       # add a new book
       path('add/book/',AddView.as_view(),name ='bookadd' ),
       #update book
       path('update/<int:id>/',updateView.as_view(), name='bookupdate'),
       #delete book
       path('delete/<int:id>/', deleteView.as_view(), name='bookdelete'),
       #for student registration
#       path('std/registration/', views.students, name="students"),
       #for student login
        path('std/login/', views.stdlogin, name='stdlogin'),
       #for std details
       path('students/', views.studentsdetails, name="students"),
       #add std
       path('students/add/', views.studentadd, name='std_add'),

       #for borrows books
       path('borrow/', views.borrow, name="borrow"),

       #to return book
       path('return/',views.returning,name='returning'),
       # update student
       path('update/std/<int:id>/', updatestdView.as_view(), name='studentupdate'),
       # delete book
       path('delete/std/<int:id>/', deletestdView.as_view(), name='studentdelete'),
       #for addditional purpose
      # path('user/login/', views.login, name="user"),
      # path('signup/user/', views.register, name='signup_user'),
      # path('logout/', views.logout, name='logout'),

       #for available books to students
#      path('available/books/',views.Bookavailable,name='bookavailable'),
       #for issue book
#       path('issue/<int:id>/', deleteView.as_view(), name='issue'),
       # for std details
#       path('std/list/',stdlistview.as_view(), name='stdlist'),
       # for std details
#       path('std/detail/<int:id>/',stddetailview.as_view(),name='stddetails'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('library.urls'),name = 'library'),
    path('login/',LoginView.as_view(),name = 'login'),
  #  path('students/add/', views.studentadd, name='std_add'),
  #  path('std/login/', views.stdlogin, name="stdlogin"),
   # path('accounts/', include('django.contrib.auth.urls'))
   # path('^accounts/login/', views.login, name='login'),
    #path('^accounts/logout/', views.logout, name='logout', kwargs={'next_page': '/'})


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/library/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date




# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    book_type = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    language = models.CharField(max_length=80)
    cover = models.TextField(max_length=100000, blank=True, null=True)
    description = models.TextField(max_length=25000, blank=True, null=True)
    available = models.IntegerField(default=0)

    # user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("library:book_detail", kwargs={"id": self.id})



   # def __str__(self):
   #    return  self.borrower
   # @property
   # def is_overdue(self):
   #     if self.due_back and date.today() > self.due_back:
   #         return True
   #     return False
class Student(models.Model):
   # student_id = models.CharField(max_length=100,unique=True,null=True)
    firstname = models.CharField(max_length=100, default="", )
    lastname = models.CharField(max_length=100, default="", )
    department = models.CharField(max_length=100, default="", )
    section = models.CharField(max_length=50, default="")
    year = models.IntegerField()
    picture = models.ImageField(upload_to='pictures/',blank=True)

    def __str__(self):
        return self.firstname +' ' +self.lastname


class Borrow(models.Model):
    book = models.ManyToManyField(Book)
    student = models.ManyToManyField(Student)
    qty = models.IntegerField(default=0)
    date = models.DateField(default=date.today)
    status = models.CharField(max_length=25)

    def __str__(self):
        return str(self.book)

mysite/library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User
from  django.core.exceptions import ValidationError
from .models import *
from django import forms

class Studentform(forms.Form):
   # student_id = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter student id'}),required=True, max_length=50)
    firstname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter first name'}),  required=True, max_length=50)
    lastname = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter last name'}), required=True, max_length=50)
    department = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter department'}), required=True, max_length=50)
    section = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter section'}), required=True),
    year = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'enter year'}), required=True)
    picture = forms.ImageField()

   # def clean_student_id(self):
   #    sid = self.cleaned_data['student_id']
   #    qs = Student.objects.filter(student_id = sid)
   #    if qs.exists():
   #      raise ValidationError("Id is already taken")
   #    return sid


'''
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user
'''
'''
    def clean_email(self):
        email = self.cleaned_data['email']
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise ValidationError('Email is already registered.')
        return email


    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get('password1')
        p2 = cleaned_data.get('password2')

        if p1 and p2:
            if p1 != p2:
                raise ValidationError('Passwords Do Not Match')
'''

mysite/library/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse,reverse_lazy
from django.http import HttpResponseRedirect,HttpResponse
from .models import Book,Student,Borrow
from django.views.generic import ListView ,CreateView,DetailView, DeleteView, UpdateView
from .forms import Studentform
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages,auth
from django.contrib.auth.models import User
from django.db.models import Sum
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .forms import UserCreationForm


# Create your views here.
def home(request):
   return render(request,"library/index.html")
#for contact
def contact(request):
   return render(request,"library/contact.html")
#for about us
def about(request):
   return render(request,"library/about.html")
#def admin(request):
#    return render(request,"library/base2.html")
#view the book

# @user_passes_test(lambda u: u.is_superuser)
@login_required(login_url='/login/')
def booklist(request):
    if  request.user.is_superuser:
        books = Book.objects.all()
        context = {
            'books': books
        }
        return render(request, 'library/book_list.html',context)
    else:
        return HttpResponseRedirect("/login/")

 #class booklistview(LoginRequiredMixin,ListView):
 #  template_name = 'library/book_list.html'
 #   queryset = Book.objects.all()
  #  login_url = "/std/login"
  #  redirect_field_name = "hollaback"
  #  raise_exception = True


#detail view
def bookdetails(request,id=None):
    book = Book.objects.get(id=id)
    context = {
        'book': book
    }
    return render(request,'library/book_detail.html',context)


#  class bookdetailview(DetailView):
#     template_name = 'library/book_detail.html'
#    def get_object(self):
#        id_ = self.kwargs.get("id")
#        return get_object_or_404(Book, id=id_)


#add a book

class AddView(CreateView):

    template_name = 'library/book_add.html'
   # form_class = BookForm
    queryset = Book.objects.all()
    fields = ['title','book_type','author','language']

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)



#update book
class updateView(UpdateView):
     template_name = 'library/book_add.html'
    # form_class = BookForm
     fields = ['title', 'book_type', 'author', 'language']
    # queryset= Book.objects.all()

     def get_object(self):
         id_ = self.kwargs.get("id")
         return get_object_or_404(Book, id=id_)


class deleteView(DeleteView):
    template_name = 'library/book_delete.html'
    # form_class = BookForm
    fields = ['title', 'book_type', 'author', 'language']
    success_url = reverse_lazy('library:book_list')

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Book, id=id_)

#for std login


def stdlogin(request):

    if request.method == "POST":

        student_id = request.POST.get('student_id')
        firstname = request.POST.get('firstname')
        student = authenticate(request,student_id=student_id, firstname=firstname)
        if student is not None:
            login(request, student)
            return redirect("library:bookavailable")
    return render(request, "library/stdform.html")
   # else:
   #     context =  "invalid username or password"
   #     return render(request,'library/stdform.html',{context:'context'})




#for student registration



def studentsdetails(request):
        students = Student.objects.all()
        context = {
            'students': students
        }
        return render(request, 'student/std_form.html',context)
       # students = Student.objects.all()
       # return render(request, 'student/std_form.html', {"students": students})

#for adding std
def studentadd(request):
   # saved = False
   # my_form = Studentform
    if request.method == "POST":
        studentform = Studentform(request.POST,request.FILES)
        if studentform.is_valid():
              student = Student()
#              student.student_id = studentform.cleaned_data["student_id"]
              student.firstname = studentform.cleaned_data["firstname"]
              student.lastname = studentform.cleaned_data["lastname"]
              student.department = studentform.cleaned_data["department"]
              student.year = studentform.cleaned_data["year"]
              student.picture = studentform.cleaned_data["picture"]
              student.save()
              return redirect('/students/')
      #  sid = request.POST["student_id"]
      #  firstname = request.POST["firstname"]
      #  lastname = request.POST["lastname"]
      #  department = request.POST["department"]
       # year = request.POST["year"]
       # profile = request.POST.get("profile",False)
       # student = Student(student_id=sid, firstname=firstname, lastname=lastname, department=department, year=year,profile=profile)
       # student.save()
       # return redirect(reverse('library:students'))
    else:
        form = Studentform
        return render(request, 'student/signup_form.html',{'form':form})


#for additional view


#for additional purposes

#for borrowing books
def borrow(request):
    if request.method == "POST":
        student_id = request.POST['student_id']
        student = Student.objects.get(id=student_id)
        status = "Borrowed"
        books_id = request.POST.getlist('selector')
        for book_id in books_id:
            book = Book.objects.get(id=book_id)
            b = Borrow(qty=1, status=status)
            b.save()
            b.student.add(student)
            b.book.add(book)
            return redirect("library:borrow")
    students = Student.objects.all()
    books = Book.objects.all()
    datas = []
    for book in books:
        left = Borrow.objects.filter(status="Borrowed", book__title=book.title).aggregate(Sum('qty'))
        if left['qty__sum'] is None:
            l = -1
        else:
            l = int(left['qty__sum'])
        datas.append(book.available - l)
    return render(request, "student/borrow.html", {"datas": zip(books, datas), "students": students})

#to return book

def returning(request):
    if request.method == "POST":
        b_id = int(request.POST["borrow_id"])
        borrow = Borrow.objects.get(id=b_id)
        borrow.date = datetime.now()
        borrow.status = "Returned"
        borrow.save()
        return redirect('library:returning')
    borrows = Borrow.objects.all()
    return render(request, "student/return.html", {"borrows": borrows})

#for std update
class updatestdView(UpdateView):
    template_name = 'student/student_update.html'
    # form_class = BookForm
    fields = ['firstname','lastname','department','year','picture']
    success_url = reverse_lazy('library:students')

    # queryset= Book.objects.all()


    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Student, id=id_)



class deletestdView(DeleteView):
    template_name = 'student/std_delete.html'
    #fields = ['student_id','firstname','lastname','department','year','profile']
    success_url = reverse_lazy('library:students')


    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Student, id=id_)



#def Bookavailable(request):
#    book = Book.objects.all()
 #   bookinstance = BookInstance.objects.all()
 #   context = {'book':book,bookinstance:'bookinstance'}
 #   return render(request,'student/bookinstance.html',context)


#for issue book
#class deleteView(DeleteView):
 #   template_name = 'student/book_issue.html'
    # form_class = BookForm
  #  fields = ['book_name', 'book_type', 'author', 'language']
   # success_url = reverse_lazy('library:bookavailable')

#    def get_object(self):
##        return get_object_or_404(Book, id=id_)

# for std list
#class stdlistview(ListView):
#    fields = ['book_name', 'book_type', 'author', 'language']
#    template_name = 'student/stdlist.html'
 #   queryset = Book.objects.all()
#class stddetailview(DetailView):
#    template_name = 'student/std_detail.html'

 #   def get_object(self):
 #       id_ = self.kwargs.get("id")
 #       return get_object_or_404(Book, id=id_)

mysite/library/templates/library/about.html
{% extends 'library/base.html' %}
 <title>{% block title %}about{% endblock %}</title>
{% block body %}
<div class="container">
    <h1 style=" color:black">About library management system </h1>
    <br>
    <p>Library management is a sub-discipline of institutional management that focuses on specific issues faced by libraries and library management professionals. Library management encompasses normal managerial tasks, as well as intellectual freedom and fundraising responsibilities. Issues faced in library management frequently overlap with those faced in managing non-profit organizations.
        The basic functions of library management include, but are not limited to: planning and negotiating the acquisition of materials, Interlibrary Loan (ILL) requests, stacks maintenance, overseeing fee collection, event planning, fundraising, and human resources.
        <br>An important aspect of library management is planning and maintaining library facilities. Successful planning is defined as "active planning that ensures an organization will have the right people in the right place at the right time for right job". Planning the construction of new libraries or remodeling those that exist is integral since user needs are often changing.</br>
     <br><footer  style="text-align:center; font-size:15px;  background-color: #80ff00">copyright and copy,2018</footer>
    </p>


</div>
{% endblock %}

mysite/library/templates/library/adminbase1.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>
    <!--load the static files-->

    {% load static %}
         <!-- Latest compiled and minified CSS -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
         <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
         <link rel="stylesheet" type="text/css" href="{% static 'library/style.css' %}">

    <!-- jQuery library
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
         Latest compiled JavaScript
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
</head>
<body>
            <nav class="navbar navbar-dark " style="background-color:#000080">
              <div class="container-fluid">
                <div class="navbar-header">
                  <a class="navbar-brand" href="/">Home</a>
                  <a class="navbar-brand" href="{% url 'library:contact' %}">Contact</a>
                  <a class="navbar-brand" href="{% url 'library:about' %}">About us</a>

                </div>
                 <ul class="nav navbar-nav navbar-right">
                  <!-- <li style="color:white"><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span> Admin</a></li>
                   <li style="color:white"><a href="#"><span class="glyphicon glyphicon-plus-sign"></span>Student</a></li>-->
                     <a class="navbar-brand" href="{% url 'login' %}"><i class="fa fa-user" aria-hidden="true"></i> Admin</a>
                 <!--    <a class="navbar-brand" href="#"><i class="fa fa-users" aria-hidden="true"></i> student</a>-->
                 </ul>

            </nav>

 <nav class="navbar navbar-expand-lg navbar-light bg-warning">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="float-left">


              <a class="navbar-brand" href="{% url 'library:book_list' %}">Book list</a>
             <!-- <a class="navbar-brand" href="{% url 'library:bookadd' %}">Add book</a>-->
              <a class="navbar-brand" href="{% url 'library:students' %}">Student</a>

          </div>


          <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          </div>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'login' %}">Logout</a>

              </li>
            </ul>
 </nav>

         <!--   <nav class="navbar navbar-expand-lg navbar-light bg-warning">

              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav ">
                  <li class="nav-item active">
                    <a class="nav-link " href="{% url 'library:book_list' %}">Book list <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'library:bookadd' %}">Add book</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}">logout</a>
                  </li>


                </ul>

              </div>
            </nav>-->


{% block body2 %}
{% endblock %}

</body>
</html>

mysite/library/templates/library/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>
    <!--load the static files-->

    {% load static %}
         <!-- Latest compiled and minified CSS -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
         <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
         <link rel="stylesheet" type="text/css" href="{% static 'library/style.css' %}">

    <!-- jQuery library
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
         Latest compiled JavaScript
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
</head>
<body>
            <nav class="navbar navbar-dark " style="background-color:#000080">
              <div class="container-fluid">
                <div class="navbar-header">
                  <a class="navbar-brand" href="/">Home</a>
                  <a class="navbar-brand" href="{% url 'library:contact' %}">Contact</a>
                  <a class="navbar-brand" href="{% url 'library:about' %}">About us</a>

                </div>
                 <ul class="nav navbar-nav navbar-right">

                     <a class="navbar-brand" href="{% url 'login' %}"><i class="fa fa-user" aria-hidden="true"></i> Admin</a>
                   <!--  <a class="navbar-brand" href="{% url 'library:stdlogin' %}"><i class="fa fa-users" aria-hidden="true"></i> student</a>-->
                 </ul>

            </nav>




{% block body %}
{% endblock %}

</body>
</html>

mysite/library/templates/library/book_add.html
{% extends 'library/adminbase1.html' %}
 <title>{% block title %}add_book{% endblock %}</title>
{% block body2 %}
   <h1 class="text-dark">Add book</h1>
  <div class="jumbotron">
      <div class="container">

            <form method="POST">{% csrf_token %}
            {{ form.as_p }}
             <button type="submit" class="save btn btn-success">Save</button>
            </form>

      </div>
   </div>
{% endblock %}

mysite/library/templates/library/book_delete.html
{% extends 'library/adminbase1.html' %}
<title>{% block title %}delete_book{% endblock %}</title>
{% block body2 %}
  <div class="jombotron">
    <form action='.' method='POST'>{% csrf_token %}
       <div class=""> <h1 style="color:black;">Do you want to delete this {{object.title}} ?</h1>
        <p style="text-align:center">
            <button class="btn btn-success">Yes</button>
            <button class="btn btn-dark"><a href="{% url 'library:book_list' %}">cancel</a></button>
        </p>
       </div>

    </form>
  </div>
{% endblock %}

mysite/library/templates/library/book_detail.html
{% extends 'library/adminbase1.html' %}
 <title>{% block title %}bookdetail{% endblock %}</title>
{% block body2 %}
<br>

<body>
    <div class="container">
        <table class="table table-striped table-bordered">
            <tr class="bg-success">
                 <th>title</th>
                 <th>book_type</th>
                 <th>author</th>
                 <th>language</th>
            </tr>
            <tr class="bg-light">
                <td> {{ book.title }}</td>
                <td> {{ book.book_type }}</td>
                <td> {{ book.author }}</td>
                <td> {{ book.language }}</td>



            </tr>
         </table>
    </div>
</body>
{% endblock %}

mysite/library/templates/library/book_list.html
{% extends 'library/adminbase1.html' %}
 <title>{% block title %}booklist{% endblock %}</title>
{% block body2 %}
<br>
         <div class="container card ">
             <div class="float-right">
                <a href="/add/book/" class="btn btn-success">Add new book</a>
             </div>

              <div class="bg-primary">
                <h1 class="card-header" style="color:black;">Book list</h1>
              </div>
           <div class="card-body">
            {% for element in books %}
              <div class="bg-light">
                  <div class="text-dark">{{element.id}}.<a href="{% url 'library:book_detail' id=element.id  %}">{{element.title }}</a></div>
                 <div class="text-right">
                    <button type="submit" class="save btn btn-dark"><a href="{% url 'library:bookupdate' id=element.id %}">update</a></button>
                    <button type="submit" class="save btn btn-danger"><a href="{% url 'library:bookdelete' id=element.id %}">Delete</a></button></p>
                 </div>
              </div>
            {% endfor %}
           </div>
         </div>
{% endblock %}

mysite/library/templates/library/contact.html
{% extends 'library/base.html' %}
 <title>{% block title %}contact{% endblock %}</title>
{% block body %}

 <body>
  <div class="container">
      <h1 style="color:green; text-align: center;">Contact information</h1>
      <br>
      <h4>Thank you for reaching out to the Little Free Library team.</h4>
      <br>
      <p> <i class="fa fa-phone" aria-hidden="true"></i>  Phone number:123456789
       <br>
        <i class="fa fa-envelope" aria-hidden="true"></i> GMAIL:example123@gmail.com</p>
       <br>
      <b>We respond to emails and phone calls received between the hours of 9 a.m. and 4 p.m.</b>
       <br>
       <br>

       </p>

  </div>
 </body>
{% endblock %}

mysite/library/templates/library/index.html
{% extends 'library/base.html' %}
 <title>{% block title %}Home{% endblock %}</title>
{% block body %}

 <div class="bg-info"><h1 style="color:	#000000">WELCOME TO PUBLIC LIBRARY</h1></div>
 <!-- <div class="images">
    {% load static %}
    <img src="{% static 'images/library.png' %}"  alt="group-work" style="width:100%;height:100%;">

  </div>-->
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'images/library.png' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/slide2.png' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="..." alt="Third slide">
    </div>
  </div>
</div>
{% endblock %}

mysite/library/templates/library/stdform.html
{% extends 'library/base.html' %}
 <title>{% block title %}login{% endblock %}</title>
{% block body %}
   <title>stdform</title>

    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-3">
             {% if messages %}

                      {% for message in messages %}
                         <div class="text-dark"><li>{{ message }}</li></div>
                      {% endfor %}

                  {% endif %}
            <br>
           <div class="card">
              <div class=" card-header bg-success text-light text-default ">Student Login</div>

                  <form method="post" action="{% url 'library:stdlogin' %}">
                      {% csrf_token %}
                      <div class="form-group">
                        <label for="student_id">Student_id</label>
                        <input type="text" class="form-control" name="sid"  placeholder="Enter id">
                      </div>
                      <div class="form-group">
                        <label for="first_name">First_name</label>
                        <input type="text" class="form-control" name="first_name" placeholder="Enter your first name">
                      </div>
                      <button type="submit" class="btn btn-info">Submit</button>
                  </form>
                  <p>Need an account? <a href="{% url 'library:students' %}">Register Here!</a></p>
              </div>
           </div>
        </div>
      </div>
{% endblock %}

mysite/library/templates/library/stdregistration.html
{% extends 'library/base.html' %}
 <title>{% block title %}student_form{% endblock %}</title>
{% block body %}
<body>


  <div class="container">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <div class="card">
          <div class=" bg-success"><h1 style="text-align:center; color:black">Signup here</h1></div>
          <br>
                <form action="" method="post">
                  {% csrf_token %}
                  {% for field in form %}
                    <div class="form-group">
                      {{ field.errors }}
                      {{ field.label_tag }}
                      {{ field }}
                    </div>
                  {% endfor %}

                  <input type="submit" value="submit" class="btn btn-warning btn-lg btn-block">
                </form>
        </div>
        </div>
      </div>
    </div>
  </div>

  </body>

  {% endblock %}

'''